config/routes.rb
Rails.application.routes.draw do
  resources :clubs
  resources :leagues

  root 'randomizer#index'

  resources :randomizer, only: [:index, :create]
  resources :matches, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :league

  def self.get_two_random_from_leagues(league_ids)
    ids = self.where(league_id: league_ids).pluck(:id).sample(2)
    self.where(id: ids)
  end
end

app/models/league.rb
class League < ApplicationRecord
  BIG_LEAGUES_IDS = [4,8,10,15].freeze

  has_many :clubs

  def self.get_samples_without_four_big_leagues(amount)
    ids = self.where.not(id: BIG_LEAGUES_IDS).pluck(:id).sample(amount)
    self.where(id: ids)
  end


  def self.get_four_big_leagues
    self.where(id: BIG_LEAGUES_IDS)
  end
end

app/models/match.rb
class Match < ApplicationRecord
  enum result: [ :tie, :home, :away ]

  belongs_to :home_club, class_name: 'Club'
  belongs_to :away_club, class_name: 'Club'

  after_create :calculate_winner

  def calculate_winner
    self.result = 'tie' if home_result == away_result
    self.result = 'home' if home_result > away_result
    self.result = 'away' if home_result < away_result
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name, :league_id)
    end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def league_params
      params.require(:league).permit(:name)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def create
    @match = Match.create(match_params)
    redirect_to :root
  end

  def match_params
    params.require(:match).permit(:home_club_id, :away_club_id, :home_result, :away_result)
  end
end

app/controllers/randomizer_controller.rb
class RandomizerController < ApplicationController
  def index
    @matches = Match.all.order(created_at: :asc)
    @kreko_won = @matches.where('home_result > away_result').count
    @pendzo_won = @matches.where('away_result > home_result').count
    @random_leagues = League.get_samples_without_four_big_leagues(3)
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def create
    random_clubs = get_random_clubs

    @match = Match.new(home_club: random_clubs.first, away_club: random_clubs.second)
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end


  private

  def league_ids_from_params
    params[:league_ids].split(',')
  end


  def get_random_clubs
    case params[:random_type]
    when 'four_big_clubs'
      random_clubs = Club.get_two_random_from_leagues(League.get_four_big_leagues.ids)
    when 'random_leagues'
      random_clubs = Club.get_two_random_from_leagues(league_ids_from_params)
    end
    random_clubs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def resolve_class(m)
   case m.result
   when 'tie'
     'yellow'
   when 'home'
     'blue'
   when 'away'
     'red'
   end
 end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/clubs/_form.html.erb
<%= form_with(model: club, local: true) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
        <% club.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :league_id %>
    <%= form.text_field :league_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>League</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.id %></td>
        <td><%= club.name %></td>
        <td><%= club.league.name %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<p>
  <strong>League:</strong>
  <%= @club.league_id %>
</p>

<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FifaMatchRandomizer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/leagues/_form.html.erb
<%= form_with(model: league, local: true) do |form| %>
  <% if league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
        <% league.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leagues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form', league: @league %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @league.name %>
</p>

<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>

app/views/matches/_match_form.html.erb
<%= form_with model: @match, class: "form" do |f| %>
  <table class='table table-light'>
    <tr>
      <th> Home Team </th>
      <th> Away Team </th>
      <th> Home Score </th>
      <th> Away Score </th>
    </tr>
    <tr>
      <td> <h3><%= @match.home_club.name %>
      <%= f.hidden_field :home_club_id, value: @match.home_club.id %>
    </h3> </td>
      <td> <h3><%= @match.away_club.name %>
      <%= f.hidden_field :away_club_id, value: @match.away_club.id %> </h3></td>
      <td> <%= f.text_field :home_result, class: 'form-control', value: 0 %> </td>
      <td> <%= f.text_field :away_result, class: 'form-control', value: 0%> </td>
      <td>   <%= f.submit "Log match" %> </td>
    </tr>
  </table>
<% end %>

app/views/randomizer/_match.html.erb
  <div class="row p-4 match">
    <div class="col match-club">
      <div class="match-summary pb-3">
        <%= image_tag 'kreko.png', class: "image-player" %>
      </div>
      <h3 class="match-summary club-name"> <%= match.home_club.name %> </h3>
      <p class="match-summary club-league-name"> <%= match.home_club.league.name %> </p>
    </div>
     <div class="col match-club">
       <div class="match-summary pb-3">
         <%= image_tag 'pendzo.jpg', class: "image-player" %>
       </div>
       <h3 class="match-summary club-name"> <%= match.away_club.name %> </h3>
       <p class="match-summary club-league-name"> <%= match.away_club.league.name %> </p>
     </div>
  </div>

app/views/randomizer/_random_team_form.html.erb
<%= form_with url: randomizer_index_path, method: :post, remote: true do |f| %>
       <%= f.hidden_field :league_ids, id: 'league_ids_field', value: random_leagues.pluck(:id).join(',') %>
       <%= f.hidden_field :random_type, value: 'random_leagues' %>
       <%= f.submit 'Generate random from 4 random leagues', class: 'btn btn-success' %>
      <% end %>
      <p class='mt-1'> Current Random Leagues are <%= random_leagues.pluck(:name).join(',') %>
        <%= link_to root_url, remote: true do %>
          &#8635;
        <% end %>
      </p>

app/views/randomizer/create.js.erb
$('#result').html('<%=j render 'match', match: @match %>'); // in HTML
$('#dynamic-match-logger').html('<%=j render "matches/match_form", match: @match %>'); // in HTML

app/views/randomizer/index.html.erb
<div class="row p-3 m-3">
  <div class="col-lg-12 m-1">
    <div class="row">
      <div class="col">
        <div class="" id="result">
          <div class="row p-4 match">
            <div class="col match-club">
              <div class="match-summary pb-3">
                <%= image_tag 'kreko.png', class: "image-player" %>
              </div>
              <h3 class="match-summary club-name"> Club 1 </h3>
              <p class="match-summary club-league-name"> League </p>
            </div>

             <div class="col match-club">
               <div class="match-summary pb-3">
                 <%= image_tag 'pendzo.jpg', class: 'image-player' %>
               </div>
               <h3 class="match-summary club-name"> Club 1 </h3>
               <p class="match-summary club-league-name"> League </p>
             </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row p-4 mt-4 match">
      <!-- <div class="col">
        <%= tag.button class: "btn btn-success", onclick: "handle_submit()" do %>
          Generate random from selected leagues
        <% end %>
      </div> -->
      <div class="col text-center">
        <%= form_with url: randomizer_index_path, method: :post, remote: true do |f| %>
         <%= f.hidden_field :random_type, value: 'four_big_clubs' %>
         <%= f.submit 'Generate random from 4 big leagues', class: 'btn btn-success' %>
        <% end %>
      </div>
      <div class="col text-center" id="random-leagues-selector" >
        <%= form_with url: randomizer_index_path, method: :post, remote: true do |f| %>
         <%= f.hidden_field :league_ids, id: 'league_ids_field', value: @random_leagues.pluck(:id).join(',') %>
         <%= f.hidden_field :random_type, value: 'random_leagues' %>
         <%= f.submit 'Generate random from 4 random leagues', class: 'btn btn-success' %>
        <% end %>
        <p class='mt-1'> Current Random Leagues are <%= @random_leagues.pluck(:name).join(',') %> </p>
      </div>
    </div>
    <!-- <div class="row">
      <div class='col button-box' style="position:relative">
        <%= tag.button class: "big-red-button", onclick: "handle_submit()" do %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class='col text-center' style="position:relative">
        <h3 class="press-the-button"> Press the big ass red button </h3>
      </div>
    </div> -->
  </div>


  <!-- <div class="col-lg-3 m-1">
    <%= form_with url: randomizer_index_path, method: :post, remote: true, id: "myform" do |f| %>
     <%= f.hidden_field :league_ids, id: 'league_ids_field'%>
    <% end %>


    <ul class="list-group">
      <% League.all.select(:id, :name).each do |league| %>
        <%= tag.li class: "list-group-item team-option", onclick: "handle_event(event);", data: { league_id: league.id } do %>
          <%= league.name %>
        <% end %>
      <% end %>
    </ul>
  </div> -->

</div>

<div class="row p-3 m-3">
  <div class="col">
    <div class="" id="dynamic-match-logger"></div>


  </div>
</div>

<div class="row p-3 m-3">
  <div class="col">
    <div class="card">
      <div class="card-body text-center">

        <h1> KREKO <span class="small-text"> <%= " #{@kreko_won} : #{@pendzo_won} " %></span> PENDZO </h1>
      </div>
    </div>
  </div>
</div>

<div class="row p-3 m-3">
  <div class="col">
    <div class="" id="all_results"></div>
    <table class='table table-light'>
      <tr>
        <th> Num of game </th>
        <th> Home Team </th>
        <th> Away Team </th>
        <th> Home Score </th>
        <th> Away Score </th>
        <th> Date Logged </th>
      </tr>
      <% @matches.each_with_index do |m, index| %>
        <%= content_tag :tr, class: resolve_class(m) do %>
          <td>  <%= index+1 %></td>
          <td>  <%= m.home_club.name %> </td>
          <td>  <%= m.away_club.name %> </td>
          <td>  <%= m.home_result %> </td>
          <td>  <%= m.away_result %></td>
          <td>  <%= m.created_at.in_time_zone('Europe/Sarajevo').strftime("%d/%m/%y %H:%M") %></td>
        <% end %>
      <% end %>
  </div>
</div>


<%= javascript_tag do %>
  function handle_event(event) {
    var target = event.target;
    target.classList.toggle('active');
  }

  function handle_submit() {
    var elements = $(".active").toArray().map(x => x.dataset.leagueId);
    if (elements.length == 0) {
      window.alert("Brah select something pls");
      return
    }
    document.getElementById("league_ids_field").value = elements
    form = document.querySelector('#myform');
    Rails.fire(form, 'submit');
  }
<% end %>